import { createContext, useContext, useMemo, useState } from 'react';
import { ageFromBirthdate, bmi, bmiStatus, healthyWeightRange } from '../utils/health';
const AppContext=createContext();
const sampleUser={firstName:'Alex',lastName:'García',email:'alex@fittrainer.app',sex:'Masculino',birthdate:'1992-04-12',weight:90,height:178,activityLevel:'Ligero',goal:'Perder peso'};
const sampleBody=[{date:'2026-06-01',weight:92,height:178,waist:101,hip:105,chest:104,arm:34,thigh:59,notes:'Inicio del plan'},{date:'2026-06-14',weight:90,height:178,waist:98,hip:103,chest:105,arm:35,thigh:60,notes:'Mejor energía'}];
const sampleWorkouts=[{date:'2026-06-18',routine:'Entrenamiento de Estrés Compuesto',duration:28,calories:245,exercises:12},{date:'2026-06-20',routine:'Entrenamiento de Estrés Compuesto',duration:30,calories:261,exercises:12}];
export function AppProvider({children}){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('fit.user')||'null')||sampleUser);const [bodyLogs,setBodyLogs]=useState(sampleBody);const [workouts,setWorkouts]=useState(sampleWorkouts);const [settings,setSettings]=useState(()=>JSON.parse(localStorage.getItem('fit.settings')||'{"sound":true}'));const [goals,setGoals]=useState({targetWeight:75,weeklyCalories:900,workoutsPerWeek:3,weeklyMinutes:90});
 const updateUser=(next)=>{setUser(next);localStorage.setItem('fit.user',JSON.stringify(next));}; const updateSettings=(next)=>{setSettings(next);localStorage.setItem('fit.settings',JSON.stringify(next));};
 const metrics=useMemo(()=>{const currentBmi=bmi(user.weight,user.height);const range=healthyWeightRange(user.height);const diff=+(user.weight-goals.targetWeight).toFixed(1);const totalToLose=Math.max(1, sampleBody[0].weight-goals.targetWeight);const progress=Math.min(100,Math.max(0,((sampleBody[0].weight-user.weight)/totalToLose)*100));const weekCalories=workouts.reduce((s,w)=>s+w.calories,0);return {age:ageFromBirthdate(user.birthdate),bmi:currentBmi,bmiStatus:bmiStatus(currentBmi),range,diff,progress:+progress.toFixed(0),weekCalories,monthCalories:weekCalories,completed:workouts.length,totalMinutes:workouts.reduce((s,w)=>s+w.duration,0),streak:2};},[user,goals,workouts]);
 return <AppContext.Provider value={{user,updateUser,bodyLogs,setBodyLogs,workouts,setWorkouts,settings,updateSettings,goals,setGoals,metrics}}>{children}</AppContext.Provider>}
export const useApp=()=>useContext(AppContext);
